[package]
name = "yuntun-wal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yuntun-model = { path = "../model" }
arrow = { workspace = true }
prost = { workspace = true }
uuid = { workspace = true }
crc32fast = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
