[package]
name = "yuntun-sqlwire"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yuntun-sql = { path = "../sql" }
arrow = { workspace = true }
async-trait = { workspace = true }
opensrv-mysql = "0.7"
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
