[package]
name = "yuntun-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yuntun-model = { path = "../model" }
object_store = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
